### ISSUE TITLE
Proposal for multi-variant testing on Voice and Tone

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/aurora-website#177]
To determine voice and tone of our brand, and what guidelines to include in the design system - we should conduct user tests to determine the tone of writing that resonates best with users and best promotes comprehension and prevents errors.

The best way to do this would be multi-variant testing writing similar content but using different tones, and evaluating user's reactions, comprehension and feedback on each variation.

**Comment by MGoodberry** [comment]
@LemieuxGen Proposal 
[Tone Testing Proposal.docx](https://github.com/gctools-outilsgc/design-system-code/files/2733934/Tone.Testing.Proposal.docx)

**Comment by Troy-Lawson** [comment]
waiting for the narrative

**Comment by s-duffey** [comment]
Proposal done and is found here: https://gcdocsp.tbssct.local/gcdocs/llisapi.dll?func=ll&objaction=overview&objid=33576843
