### ISSUE TITLE
Flash of immense SVGs

### ISSUE THREAD

**Issue by jkshapiro** [gctools-outilsgc/aurora-website#223]
Hi there,

When I load any page in Aurora (e.g. https://design.gccollab.ca/component/overall-design-and-labels/), the SVG images at top right (GitHub logo and download image), as well as the down-pointing chevrons in the left navigation bar, initially appear at a very large size before shrinking down to their proper size and making room for the rest of the page.

Details of sizing and timing differ among browsers and with caching, but this typically lasts about 500ms.

Tested with Firefox, Chrome, and Internet Explorer on Windows 7.

**Comment by RobJohnston** [comment]
This might help:
https://www.sarasoueidan.com/blog/svg-style-inheritance-and-fousvg/

**Comment by Troy-Lawson** [comment]
closed as duplicate issue
