### ISSUE TITLE
SVG icons default to 100% width and height causing jarring transitions when loading pages.

### ISSUE THREAD

**Issue by TkTech** [gctools-outilsgc/aurora-website#251]
When loading a page with icons (ex: https://design.gccollab.ca/) on cold loads or on slow connections the icons each take up the entire page until the CSS rules are loaded due to the SVGs having no default height/width. This causes page loads to be very visually jarring. The first 15 seconds of design.gcollab.ca on a mobile connection looks like this:

Firefox:

![image](https://user-images.githubusercontent.com/72590/54368478-9dc57b00-464a-11e9-93ad-2dad908f5ccf.png)

Chrome: 

![image](https://user-images.githubusercontent.com/72590/54369216-e6c9ff00-464b-11e9-92aa-190c564b90b3.png)

Quick fix for the icons inline with text is to use `style="width: 1em;"` instead of the current `style="font-size:1.5em"` (which has no effect).

**Comment by jkshapiro** [comment]
See also #223

**Comment by ethanWallace** [comment]
Closed with pull request #253
