### ISSUE TITLE
What does it mean to be complementary to other systems?

### ISSUE THREAD

**Issue by CalvinRodo** [gctools-outilsgc/aurora-website#254]
On your overview page you state that:

> Using Aurora is complementary to the Web Experience Toolkit (WET), Canada.ca Style Guide, ...

What does complementary mean in this case? 

For instance there would have to be changes made to comply with the *Canada.ca Content and Information Architecture Specification: Mandatory elements of the Canada.ca design system*.  
 
The Aurora Design System uses a different typography then the [typography](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification/mandatory-elements.html#typog) that is required to comply with the Mandatory Elements. 

Does it just mean it will work along side it, because it doesn't faithfully implement it.

**Comment by jkshapiro** [comment]
What was the resolution to this?
