### ISSUE TITLE
Search Documentation Issue

### ISSUE THREAD

**Issue by CalvinRodo** [gctools-outilsgc/aurora-website#255]
On the search page **Design** tab you have the text: 

>Text field with a padding of 12px. On the right of the field there is a search icon that serves as an action button. The icon is sized at 1.2 em and coloured with #666666.

But the example and the site itself does not have the search icon to the right of the field.

**Comment by s-duffey** [comment]
Hi @CalvinRodo thanks for noticing this! I'll make the fix. Originally we had some documentation on when to use an icon, but we removed it for now.
